### ISSUE TITLE
cuth?

### ISSUE THREAD

**Issue by namp** [facebookresearch/MIXER#1]
What on earth is "cuth"?

I installed cutorch (luarocks install cutorch) just in case, but still...

cuth -i main.lua

No command 'cuth' found, did you mean:
 Command 'cut' from package 'coreutils' (main)
cuth: command not found

**Comment by hohoCode** [comment]
I guess.. is it just "th"?

**Comment by namp** [comment]
Just by calling "th main.lua" I get a lot of error messages so maybe it's not exactly the same as "cuth"?

> th main.lua
> Start training
> nrstepsinit 25
> error in SpatialAveragePooling.updateGradInput: too many resources requested for launch
> /media/ubuntu/JetsonSSD/torch/install/bin/luajit: ...u/JetsonSSD/torch/install/share/lua/5.1/nn/Container.lua:67:
> In 3 module of nn.Sequential:
> ...ubuntu/JetsonSSD/torch/install/share/lua/5.1/nn/THNN.lua:109: aborting at /tmp/luarocks_cunn-scm-1-3993/cunn/lib/THCUNN/SpatialAveragePooling.cu:228
> stack traceback:
>     [C]: in function 'v'
>     ...ubuntu/JetsonSSD/torch/install/share/lua/5.1/nn/THNN.lua:109: in function 'SpatialAveragePooling_updateGradInput'
>     ...torch/install/share/lua/5.1/nn/SpatialAveragePooling.lua:67: in function <...torch/install/share/lua/5.1/nn/SpatialAveragePooling.lua:65>
>     [C]: in function 'xpcall'
>     ...u/JetsonSSD/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
>     .../JetsonSSD/torch/install/share/lua/5.1/nn/Sequential.lua:55: in function 'updateGradInput'
>     ...etsonSSD/torch/install/share/lua/5.1/nngraph/gmodule.lua:407: in function 'neteval'
>     ...etsonSSD/torch/install/share/lua/5.1/nngraph/gmodule.lua:441: in function 'updateGradInput'
>     ...untu/JetsonSSD/torch/install/share/lua/5.1/nn/Module.lua:31: in function 'backward'
>     /media/ubuntu/JetsonSSD/MIXER/Mixer.lua:284: in function 'train_one_batch'
>     /media/ubuntu/JetsonSSD/MIXER/Trainer.lua:66: in function 'train'
>     /media/ubuntu/JetsonSSD/MIXER/Trainer.lua:135: in function 'run'
>     main.lua:155: in main chunk
>     [C]: in function 'dofile'
>     ...nSSD/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
>     [C]: at 0x0000cfc9

WARNING: If you see a stack trace below, it doesn't point to the place where this error occured. Please use only the one above.
stack traceback:
    [C]: in function 'error'
    ...u/JetsonSSD/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
    .../JetsonSSD/torch/install/share/lua/5.1/nn/Sequential.lua:55: in function 'updateGradInput'
    ...etsonSSD/torch/install/share/lua/5.1/nngraph/gmodule.lua:407: in function 'neteval'
    ...etsonSSD/torch/install/share/lua/5.1/nngraph/gmodule.lua:441: in function 'updateGradInput'
    ...untu/JetsonSSD/torch/install/share/lua/5.1/nn/Module.lua:31: in function 'backward'
    /media/ubuntu/JetsonSSD/MIXER/Mixer.lua:284: in function 'train_one_batch'
    /media/ubuntu/JetsonSSD/MIXER/Trainer.lua:66: in function 'train'
    /media/ubuntu/JetsonSSD/MIXER/Trainer.lua:135: in function 'run'
    main.lua:155: in main chunk
    [C]: in function 'dofile'
    ...nSSD/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x0000cfc9

**Comment by ranzato** [comment]
Sorry about the cuth, it is indeed th. 
I have updated the README accordingly.

As for the error you get now, it does not seem related to the code per se but to the combination of card and CUDA version you are using, what are they?
See also: https://github.com/torch/cunn/issues/32

**Comment by namp** [comment]
Thanks for the clarification.

Indeed, the error seems to be related to the Jetson TK1 setup.
