### ISSUE TITLE
cannot load libcutorch.so even I had 'luarocks install cutorch success'

### ISSUE THREAD

**Issue by SeekPoint** [facebookresearch/MIXER#3]
envy@ub1404:~/os_pri/github/MIXER$ th -i main.lua
/home/envy/torch/install/bin/luajit: /home/envy/torch/install/share/lua/5.1/trepl/init.lua:384: /home/envy/torch/install/share/lua/5.1/cutorch/init.lua:2: cannot load '/home/envy/torch/install/lib/lua/5.1/libcutorch.so'
stack traceback:
    [C]: in function 'error'
    /home/envy/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
    main.lua:20: in main chunk
    [C]: in function 'dofile'
    ...envy/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406260
envy@ub1404:~/os_pri/github/MIXER$ 

envy@ub1404:~/os_pri/github/MIXER$ ll /home/envy/torch/install/lib/lua/5.1/libcutorch.so
-rwxr-xr-x 1 envy envy 568530  3月  9 21:09 /home/envy/torch/install/lib/lua/5.1/libcutorch.so*
envy@ub1404:~/os_pri/github/MIXER$

**Comment by soumith** [comment]
@loveJasmine could you give the output of: luajit -llibcutorch

**Comment by ranzato** [comment]
This issue seems more related to Torch & CUDA than MIXER itself. Closing the task for now.

**Comment by panfengli** [comment]
Try `sudo bash /torch/update.sh`

**Comment by MaffooBristol** [comment]
@panfengli Could you please stop posting this comment on every bloody cutorch thread?

**Comment by panfengli** [comment]
No, I couldn't. At least the method solved my situation, and might also be helpful for others.@MaffooBristol

**Comment by MaffooBristol** [comment]
@panfengli Don't get me wrong, I'm grateful for you and others offering solutions, but it's just when I'm looking around trying to find a solution and find the same copy & pasted response several times (which didn't help in my case), it's counter-helpful
