### ISSUE TITLE
does it so complicated?

### ISSUE THREAD

**Issue by SeekPoint** [facebookresearch/MIXER#8]
I use  graph.dot(net.fg, "net.fg ", "net.fg.png") and
graph.dot(net.bg, "net.bg ", "net.bg.png") 
 to draw the net graph return by
local net, size_hid_layers = mdls.makeNetSingleStep( config.model, dict_target, dict_source) at main.lua

it looks so complicated, really?

![net fg](https://cloud.githubusercontent.com/assets/18051187/25655620/1541185a-3028-11e7-89a9-916772ec0da0.jpg)
![net bg](https://cloud.githubusercontent.com/assets/18051187/25655624/17699fc6-3028-11e7-93fa-2493e494697d.jpg)

**Comment by ranzato** [comment]
I would not try to understand the architecture from this graph.
However, once you know what the architecture is, it may be useful to check this graph for debugging purposes.

This code was written well before cudnn.lstm which would greatly simplify the graph (as the computation represented by 1-step RNN would appear just as a single blob).

**Comment by SeekPoint** [comment]
I think cudnn is a deep learning provided by Nvidia， do you refer the 'cudnn.lstm' as the package of https://github.com/soumith/cudnn.torch ?
